<?php
/**
 * Template Name: Карточка предприятия
 * Template Post Type: page
 */
?>
<?php get_header(); ?>
<main class="main" role="main">
<section class="profile _section-padding"><div class="profile__container"><h1 class="_section-title"><?php echo get_field('org_page_title') ?: 'Карточка предприятия'; ?></h1><div class="profile__content"><div class="profile__info df df-jb"><div class="profile__info-item"><h3 class="_section-text"><span><?php echo get_field('org_bank_title') ?: 'Банковские'; ?></span> реквизиты:</h3><ul class="_section-text"><li><?php echo get_field('org_bank_label') ?: 'Наименование банка:'; ?></li><li><?php echo get_field('org_bank_name') ?: 'ФИЛИАЛ "НОВОСИБИРСКИЙ" АО "АЛЬФА-БАНК"'; ?></li><li><?php echo get_field('org_bank_account') ?: 'Расчетный счет: 40702810723020004017'; ?></li><li><?php echo get_field('org_bank_corr') ?: 'Корреспондентский счет: 30101810600000000774'; ?></li><li><?php echo get_field('org_bank_dept') ?: 'ОТДЕЛЕНИЕ ПО СИБИРСКОЕ ГУ БАНКА РОССИИ'; ?></li><li><?php echo get_field('org_bank_bik') ?: 'БИК: 045004774'; ?></li></ul></div><div class="profile__info-item"><h3 class="_section-text"><span><?php echo get_field('org_reg_title') ?: 'Внесена запись о создании'; ?></span> юридического лица:</h3><ul class="_section-text"><li><?php echo get_field('org_reg_line1') ?: 'Регистрационная палата Администрации'; ?></li><li><?php echo get_field('org_reg_line2') ?: 'г. Иркутска'; ?></li><li><?php echo get_field('org_reg_line3') ?: '23.01.1995 г.'; ?></li></ul></div><div class="profile__info-item"><h3 class="_section-text"><?php echo get_field('org_main_title1') ?: 'ООО &quot;Юридическая компания'; ?> <span><?php echo get_field('org_main_title2') ?: '&quot;ЕСТЬ РЕШЕНИЕ&quot;'; ?></span></h3><ul class="_section-text"><li><?php echo get_field('org_inn') ?: 'ИНН: 3811033845'; ?></li><li><?php echo get_field('org_kpp') ?: 'КПП: 380801001'; ?></li><li><?php echo get_field('org_ogrn') ?: 'ОГРН: 1023801539838'; ?></li><li><?php echo get_field('org_address') ?: 'Адрес фактический: 664007, г. Иркутск, ул. Поленова 1/1, офис 213'; ?></li></ul></div></div><a href="/payment" class="profile__btn _btn"><?php echo get_field('org_btn') ?: 'Перейти к оплате'; ?></a></div></div></section>
</main>
<?php get_footer(); ?>
