<?php
if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

// ─── О компании ───
acf_add_local_field_group( array(
	'key'   => 'group_company',
	'title' => 'О компании',
	'fields' => array(
		array(
			'key'       => 'field_company_tab_team',
			'label'     => 'Команда',
			'name'      => 'tab_team',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_company_team_title',
			'label' => 'Заголовок',
			'name'  => 'team_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_team_title_span',
			'label' => 'Заголовок (выделение)',
			'name'  => 'team_title_span',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_team_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'team_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_team_members',
			'label' => 'Члены команды',
			'name'  => 'team_members',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_company_team_members_member_image',
					'label' => 'Фото',
					'name'  => 'member_image',
					'type'  => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_company_team_members_member_name',
					'label' => 'Имя',
					'name'  => 'member_name',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_company_team_members_member_link',
					'label' => 'Ссылка',
					'name'  => 'member_link',
					'type'  => 'url',
				),
			),
		),
		array(
			'key'       => 'field_company_tab_action',
			'label'     => 'Призыв к действию',
			'name'      => 'tab_action',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_company_action_title',
			'label' => 'Заголовок',
			'name'  => 'action_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_company_action_btn',
			'label' => 'Кнопка',
			'name'  => 'action_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_company_tab_writeoff',
			'label'     => 'Блок списания',
			'name'      => 'tab_writeoff',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_company_writeoff_h1',
			'label' => 'Заголовок H1',
			'name'  => 'writeoff_h1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_writeoff_h2',
			'label' => 'Описание',
			'name'  => 'writeoff_h2',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_company_writeoff_h3',
			'label' => 'Призыв (начало)',
			'name'  => 'writeoff_h3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_writeoff_h3_span',
			'label' => 'Призыв (выделение)',
			'name'  => 'writeoff_h3_span',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_writeoff_h3_2',
			'label' => 'Призыв (продолжение)',
			'name'  => 'writeoff_h3_2',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_company_tab_callback',
			'label'     => 'Форма обратной связи',
			'name'      => 'tab_callback',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_company_callback_title',
			'label' => 'Заголовок',
			'name'  => 'callback_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_callback_title_span',
			'label' => 'Заголовок (выделение)',
			'name'  => 'callback_title_span',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-company.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Контакты ───
acf_add_local_field_group( array(
	'key'   => 'group_contacts',
	'title' => 'Контакты',
	'fields' => array(
		array(
			'key'       => 'field_contacts_tab_header',
			'label'     => 'Заголовок и форма',
			'name'      => 'tab_header',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_contacts_contacts_page_title',
			'label' => 'Заголовок страницы',
			'name'  => 'contacts_page_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_form_title',
			'label' => 'Форма: заголовок',
			'name'  => 'contacts_form_title',
			'type'  => 'textarea',
		),
		array(
			'key'       => 'field_contacts_tab_info',
			'label'     => 'Контактная информация',
			'name'      => 'tab_info',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_contacts_contacts_address_label',
			'label' => 'Адрес: метка',
			'name'  => 'contacts_address_label',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_address',
			'label' => 'Адрес',
			'name'  => 'contacts_address',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_phone_label',
			'label' => 'Телефон: метка',
			'name'  => 'contacts_phone_label',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_phone',
			'label' => 'Телефон',
			'name'  => 'contacts_phone',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_phone_note',
			'label' => 'Телефон: примечание',
			'name'  => 'contacts_phone_note',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_email_label',
			'label' => 'Почта: метка',
			'name'  => 'contacts_email_label',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_email',
			'label' => 'Email',
			'name'  => 'contacts_email',
			'type'  => 'email',
		),
		array(
			'key'   => 'field_contacts_contacts_cta',
			'label' => 'CTA текст',
			'name'  => 'contacts_cta',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-contacts.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Карточка предприятия ───
acf_add_local_field_group( array(
	'key'   => 'group_organization',
	'title' => 'Карточка предприятия',
	'fields' => array(
		array(
			'key'       => 'field_organization_tab_main',
			'label'     => 'Основные данные',
			'name'      => 'tab_main',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_organization_org_page_title',
			'label' => 'Заголовок страницы',
			'name'  => 'org_page_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_main_title1',
			'label' => 'Компания: название',
			'name'  => 'org_main_title1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_main_title2',
			'label' => 'Компания: название (выделение)',
			'name'  => 'org_main_title2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_inn',
			'label' => 'ИНН',
			'name'  => 'org_inn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_kpp',
			'label' => 'КПП',
			'name'  => 'org_kpp',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_ogrn',
			'label' => 'ОГРН',
			'name'  => 'org_ogrn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_address',
			'label' => 'Адрес фактический',
			'name'  => 'org_address',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_btn',
			'label' => 'Кнопка оплаты',
			'name'  => 'org_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_organization_tab_bank',
			'label'     => 'Банковские реквизиты',
			'name'      => 'tab_bank',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_organization_org_bank_title',
			'label' => 'Заголовок (выделение)',
			'name'  => 'org_bank_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_name',
			'label' => 'Наименование банка',
			'name'  => 'org_bank_name',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_account',
			'label' => 'Расчётный счёт',
			'name'  => 'org_bank_account',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_corr',
			'label' => 'Корреспондентский счёт',
			'name'  => 'org_bank_corr',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_dept',
			'label' => 'Подразделение',
			'name'  => 'org_bank_dept',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_bik',
			'label' => 'БИК',
			'name'  => 'org_bank_bik',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_organization_tab_reg',
			'label'     => 'Запись о создании',
			'name'      => 'tab_reg',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_organization_org_reg_title',
			'label' => 'Заголовок (выделение)',
			'name'  => 'org_reg_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_reg_line1',
			'label' => 'Строка 1',
			'name'  => 'org_reg_line1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_reg_line2',
			'label' => 'Строка 2',
			'name'  => 'org_reg_line2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_reg_line3',
			'label' => 'Дата',
			'name'  => 'org_reg_line3',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-organization.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Оплата ───
acf_add_local_field_group( array(
	'key'   => 'group_payment',
	'title' => 'Оплата',
	'fields' => array(
		array(
			'key'       => 'field_payment_tab_content',
			'label'     => 'Содержимое',
			'name'      => 'tab_content',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_payment_payment_title',
			'label' => 'Заголовок H1',
			'name'  => 'payment_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_payment_payment_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'payment_subtitle',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_payment_payment_btn',
			'label' => 'Кнопка',
			'name'  => 'payment_btn',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-payment.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── База знаний ───
acf_add_local_field_group( array(
	'key'   => 'group_help',
	'title' => 'База знаний',
	'fields' => array(
		array(
			'key'       => 'field_help_tab_content',
			'label'     => 'Заголовок',
			'name'      => 'tab_content',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_help_help_title',
			'label' => 'Заголовок',
			'name'  => 'help_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_help_help_title_span',
			'label' => 'Заголовок (выделение)',
			'name'  => 'help_title_span',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_help_tab_articles',
			'label'     => 'Статьи',
			'name'      => 'tab_articles',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_help_help_articles',
			'label' => 'Статьи',
			'name'  => 'help_articles',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_help_help_articles_article_image',
					'label' => 'Изображение',
					'name'  => 'article_image',
					'type'  => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_help_help_articles_article_text',
					'label' => 'Текст',
					'name'  => 'article_text',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_help_help_articles_article_link',
					'label' => 'Ссылка',
					'name'  => 'article_link',
					'type'  => 'url',
				),
			),
		),
		array(
			'key'       => 'field_help_tab_callback',
			'label'     => 'Форма',
			'name'      => 'tab_callback',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_help_help_callback_title',
			'label' => 'Заголовок формы',
			'name'  => 'help_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-help.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Главная страница ───
acf_add_local_field_group( array(
	'key'   => 'group_front_page',
	'title' => 'Главная страница',
	'fields' => array(
		array(
			'key'       => 'field_front_page_tab_hero',
			'label'     => 'Hero-секция',
			'name'      => 'tab_hero',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_hero_title',
			'label' => 'Заголовок H1',
			'name'  => 'hero_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_subtitle',
			'label' => 'Подзаголовок H2',
			'name'  => 'hero_subtitle',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_btn',
			'label' => 'Кнопка',
			'name'  => 'hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat1_num',
			'label' => 'Статистика 1 (число)',
			'name'  => 'hero_stat1_num',
			'type'  => 'number',
		),
		array(
			'key'   => 'field_front_page_hero_stat1_text',
			'label' => 'Статистика 1 (текст)',
			'name'  => 'hero_stat1_text',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat2_before',
			'label' => 'Статистика 2 (до)',
			'name'  => 'hero_stat2_before',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat2_num',
			'label' => 'Статистика 2 (число)',
			'name'  => 'hero_stat2_num',
			'type'  => 'number',
		),
		array(
			'key'   => 'field_front_page_hero_stat2_after',
			'label' => 'Статистика 2 (после)',
			'name'  => 'hero_stat2_after',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat3_before',
			'label' => 'Статистика 3 (до)',
			'name'  => 'hero_stat3_before',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat3_num',
			'label' => 'Статистика 3 (число)',
			'name'  => 'hero_stat3_num',
			'type'  => 'number',
		),
		array(
			'key'   => 'field_front_page_hero_stat3_after',
			'label' => 'Статистика 3 (после)',
			'name'  => 'hero_stat3_after',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_box1',
			'label' => 'Блок 1',
			'name'  => 'hero_box1',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_box2',
			'label' => 'Блок 2',
			'name'  => 'hero_box2',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_box3',
			'label' => 'Блок 3',
			'name'  => 'hero_box3',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_review1_text',
			'label' => 'Отзывы 1 (текст)',
			'name'  => 'hero_review1_text',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_review1_link',
			'label' => 'Отзывы 1 (ссылка)',
			'name'  => 'hero_review1_link',
			'type'  => 'url',
		),
		array(
			'key'   => 'field_front_page_hero_review2_text',
			'label' => 'Отзывы 2 (текст)',
			'name'  => 'hero_review2_text',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_review2_link',
			'label' => 'Отзывы 2 (ссылка)',
			'name'  => 'hero_review2_link',
			'type'  => 'url',
		),
		array(
			'key'       => 'field_front_page_tab_amnesty',
			'label'     => 'Освобождение от долгов',
			'name'      => 'tab_amnesty',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_amnesty_title',
			'label' => 'Заголовок',
			'name'  => 'amnesty_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_amnesty_cards',
			'label' => 'Карточки долгов',
			'name'  => 'amnesty_cards',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_amnesty_cards_card_num',
					'label' => 'Номер',
					'name'  => 'card_num',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_amnesty_cards_card_title',
					'label' => 'Заголовок',
					'name'  => 'card_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_amnesty_cards_card_text',
					'label' => 'Описание',
					'name'  => 'card_text',
					'type'  => 'text',
				),
			),
		),
		array(
			'key'   => 'field_front_page_amnesty_btn',
			'label' => 'Кнопка',
			'name'  => 'amnesty_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_front_page_tab_discharge',
			'label'     => 'Как списать долги',
			'name'      => 'tab_discharge',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_discharge_title',
			'label' => 'Заголовок',
			'name'  => 'discharge_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_discharge_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'discharge_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_discharge_steps',
			'label' => 'Шаги',
			'name'  => 'discharge_steps',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_discharge_steps_step_text',
					'label' => 'Шаг',
					'name'  => 'step_text',
					'type'  => 'text',
				),
			),
		),
		array(
			'key'       => 'field_front_page_tab_trust',
			'label'     => 'Почему доверяют',
			'name'      => 'tab_trust',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_trust_title',
			'label' => 'Заголовок',
			'name'  => 'trust_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_trust_items',
			'label' => 'Преимущества',
			'name'  => 'trust_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_trust_items_item_title',
					'label' => 'Заголовок',
					'name'  => 'item_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_trust_items_item_text',
					'label' => 'Текст',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_front_page_tab_action',
			'label'     => 'Призыв',
			'name'      => 'tab_action',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_action_title',
			'label' => 'Заголовок',
			'name'  => 'action_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_action_btn',
			'label' => 'Кнопка',
			'name'  => 'action_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_front_page_tab_history',
			'label'     => 'Истории клиентов',
			'name'      => 'tab_history',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_history_title',
			'label' => 'Заголовок раздела',
			'name'  => 'history_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_history_cases',
			'label' => 'Кейсы',
			'name'  => 'history_cases',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_history_cases_case_title',
					'label' => 'Заголовок',
					'name'  => 'case_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_image',
					'label' => 'Фото',
					'name'  => 'case_image',
					'type'  => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_problem',
					'label' => 'Проблема',
					'name'  => 'case_problem',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_solution',
					'label' => 'Решение',
					'name'  => 'case_solution',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_term',
					'label' => 'Срок',
					'name'  => 'case_term',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_result',
					'label' => 'Итог',
					'name'  => 'case_result',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_btn',
					'label' => 'Кнопка',
					'name'  => 'case_btn',
					'type'  => 'text',
				),
			),
		),
		array(
			'key'       => 'field_front_page_tab_case_stats',
			'label'     => 'Цифры',
			'name'      => 'tab_case_stats',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_case_stat1',
			'label' => 'Долгов списано',
			'name'  => 'case_stat1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_case_stat2',
			'label' => 'Средний срок',
			'name'  => 'case_stat2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_case_stat3',
			'label' => 'Клиентов',
			'name'  => 'case_stat3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_case_btn',
			'label' => 'Кнопка',
			'name'  => 'case_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_front_page_tab_faq',
			'label'     => 'FAQ',
			'name'      => 'tab_faq',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_faq_title',
			'label' => 'Заголовок',
			'name'  => 'faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_faq_items',
			'label' => 'Вопросы и ответы',
			'name'  => 'faq_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_front_page_tab_calc',
			'label'     => 'Калькулятор',
			'name'      => 'tab_calc',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_calc_title',
			'label' => 'Заголовок',
			'name'  => 'calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_calc_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_front_page_tab_callback',
			'label'     => 'Форма',
			'name'      => 'tab_callback',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_front_page_callback_title',
			'label' => 'Заголовок формы',
			'name'  => 'callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'front-page.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Судебное банкротство ───
acf_add_local_field_group( array(
	'key'   => 'group_court',
	'title' => 'Судебное банкротство',
	'fields' => array(
		array(
			'key'       => 'field_court_tab_hero',
			'label'     => 'Hero',
			'name'      => 'tab_hero',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_hero_title',
			'label' => 'Заголовок H1',
			'name'  => 'court_hero_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'court_hero_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_stat1',
			'label' => 'Статус 1',
			'name'  => 'court_hero_stat1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_stat2',
			'label' => 'Статус 2',
			'name'  => 'court_hero_stat2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_stat3',
			'label' => 'Статус 3',
			'name'  => 'court_hero_stat3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_btn',
			'label' => 'Кнопка',
			'name'  => 'court_hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_desc',
			'label' => 'Описание',
			'name'  => 'court_hero_desc',
			'type'  => 'textarea',
		),
		array(
			'key'       => 'field_court_tab_types',
			'label'     => 'Типы долгов',
			'name'      => 'tab_types',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_types_title',
			'label' => 'Заголовок',
			'name'  => 'court_types_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_court_types_items',
			'label' => 'Список',
			'name'  => 'court_types_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_types_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'text',
				),
			),
		),
		array(
			'key'       => 'field_court_tab_eligibility',
			'label'     => 'Кому подходит',
			'name'      => 'tab_eligibility',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_eligibility_title',
			'label' => 'Заголовок',
			'name'  => 'court_eligibility_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_eligibility_items',
			'label' => 'Пункты',
			'name'  => 'court_eligibility_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_eligibility_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_court_tab_consequences',
			'label'     => 'Последствия',
			'name'      => 'tab_consequences',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_consequences_title',
			'label' => 'Заголовок',
			'name'  => 'court_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_consequences_items',
			'label' => 'Пункты',
			'name'  => 'court_consequences_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_consequences_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_court_tab_action',
			'label'     => 'Призыв',
			'name'      => 'tab_action',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_action_title',
			'label' => 'Заголовок',
			'name'  => 'court_action_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_court_action_btn',
			'label' => 'Кнопка',
			'name'  => 'court_action_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_court_tab_stages',
			'label'     => 'Этапы',
			'name'      => 'tab_stages',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_stages_title',
			'label' => 'Заголовок',
			'name'  => 'court_stages_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_stages_items',
			'label' => 'Этапы',
			'name'  => 'court_stages_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_stages_items_stage_title',
					'label' => 'Название',
					'name'  => 'stage_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_court_stages_items_stage_term',
					'label' => 'Срок',
					'name'  => 'stage_term',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_court_stages_items_stage_desc',
					'label' => 'Описание',
					'name'  => 'stage_desc',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_court_tab_result',
			'label'     => 'Результат',
			'name'      => 'tab_result',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_result_title',
			'label' => 'Заголовок',
			'name'  => 'court_result_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_result_text',
			'label' => 'Текст',
			'name'  => 'court_result_text',
			'type'  => 'textarea',
		),
		array(
			'key'       => 'field_court_tab_faq',
			'label'     => 'FAQ',
			'name'      => 'tab_faq',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_faq_title',
			'label' => 'Заголовок',
			'name'  => 'court_faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_faq_items',
			'label' => 'Вопросы и ответы',
			'name'  => 'court_faq_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_court_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_court_tab_calc',
			'label'     => 'Калькулятор',
			'name'      => 'tab_calc',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_calc_title',
			'label' => 'Заголовок',
			'name'  => 'court_calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_calc_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'court_calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_calc_btn',
			'label' => 'Кнопка',
			'name'  => 'court_calc_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_court_tab_callback',
			'label'     => 'Форма',
			'name'      => 'tab_callback',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_court_callback_title',
			'label' => 'Заголовок формы',
			'name'  => 'court_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-court.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Детали судебного банкротства ───
acf_add_local_field_group( array(
	'key'   => 'group_court_details',
	'title' => 'Детали судебного банкротства',
	'fields' => array(
		array(
			'key'       => 'field_court_details_tab_hero',
			'label'     => 'Hero',
			'name'      => 'tab_hero',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_hero_title',
			'label' => 'Заголовок H1',
			'name'  => 'court_hero_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_hero_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'court_hero_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_hero_stat1',
			'label' => 'Статус 1',
			'name'  => 'court_hero_stat1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_hero_stat2',
			'label' => 'Статус 2',
			'name'  => 'court_hero_stat2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_hero_stat3',
			'label' => 'Статус 3',
			'name'  => 'court_hero_stat3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_hero_btn',
			'label' => 'Кнопка',
			'name'  => 'court_hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_hero_desc',
			'label' => 'Описание',
			'name'  => 'court_hero_desc',
			'type'  => 'textarea',
		),
		array(
			'key'       => 'field_court_details_tab_types',
			'label'     => 'Типы долгов',
			'name'      => 'tab_types',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_types_title',
			'label' => 'Заголовок',
			'name'  => 'court_types_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_details_court_types_items',
			'label' => 'Список',
			'name'  => 'court_types_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_court_types_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'text',
				),
			),
		),
		array(
			'key'       => 'field_court_details_tab_eligibility',
			'label'     => 'Кому подходит',
			'name'      => 'tab_eligibility',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_eligibility_title',
			'label' => 'Заголовок',
			'name'  => 'court_eligibility_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_eligibility_items',
			'label' => 'Пункты',
			'name'  => 'court_eligibility_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_court_eligibility_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_court_details_tab_consequences',
			'label'     => 'Последствия',
			'name'      => 'tab_consequences',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_consequences_title',
			'label' => 'Заголовок',
			'name'  => 'court_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_consequences_items',
			'label' => 'Пункты',
			'name'  => 'court_consequences_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_court_consequences_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_court_details_tab_action',
			'label'     => 'Призыв',
			'name'      => 'tab_action',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_action_title',
			'label' => 'Заголовок',
			'name'  => 'court_action_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_details_court_action_btn',
			'label' => 'Кнопка',
			'name'  => 'court_action_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_court_details_tab_stages',
			'label'     => 'Этапы',
			'name'      => 'tab_stages',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_stages_title',
			'label' => 'Заголовок',
			'name'  => 'court_stages_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_stages_items',
			'label' => 'Этапы',
			'name'  => 'court_stages_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_court_stages_items_stage_title',
					'label' => 'Название',
					'name'  => 'stage_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_details_court_stages_items_stage_term',
					'label' => 'Срок',
					'name'  => 'stage_term',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_details_court_stages_items_stage_desc',
					'label' => 'Описание',
					'name'  => 'stage_desc',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_court_details_tab_result',
			'label'     => 'Результат',
			'name'      => 'tab_result',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_result_title',
			'label' => 'Заголовок',
			'name'  => 'court_result_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_result_text',
			'label' => 'Текст',
			'name'  => 'court_result_text',
			'type'  => 'textarea',
		),
		array(
			'key'       => 'field_court_details_tab_faq',
			'label'     => 'FAQ',
			'name'      => 'tab_faq',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_faq_title',
			'label' => 'Заголовок',
			'name'  => 'court_faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_faq_items',
			'label' => 'Вопросы и ответы',
			'name'  => 'court_faq_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_court_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_details_court_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_court_details_tab_calc',
			'label'     => 'Калькулятор',
			'name'      => 'tab_calc',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_calc_title',
			'label' => 'Заголовок',
			'name'  => 'court_calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_calc_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'court_calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_court_calc_btn',
			'label' => 'Кнопка',
			'name'  => 'court_calc_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_court_details_tab_callback',
			'label'     => 'Форма',
			'name'      => 'tab_callback',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_court_details_court_callback_title',
			'label' => 'Заголовок формы',
			'name'  => 'court_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-court-details.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Внесудебное банкротство ───
acf_add_local_field_group( array(
	'key'   => 'group_outofcourt',
	'title' => 'Внесудебное банкротство',
	'fields' => array(
		array(
			'key'       => 'field_outofcourt_tab_hero',
			'label'     => 'Hero',
			'name'      => 'tab_hero',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_title',
			'label' => 'Заголовок H1',
			'name'  => 'ooc_hero_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'ooc_hero_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_stat1',
			'label' => 'Статус 1',
			'name'  => 'ooc_hero_stat1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_stat2',
			'label' => 'Статус 2',
			'name'  => 'ooc_hero_stat2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_stat3',
			'label' => 'Статус 3',
			'name'  => 'ooc_hero_stat3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_btn',
			'label' => 'Кнопка',
			'name'  => 'ooc_hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_desc',
			'label' => 'Описание',
			'name'  => 'ooc_hero_desc',
			'type'  => 'textarea',
		),
		array(
			'key'       => 'field_outofcourt_tab_types',
			'label'     => 'Типы долгов',
			'name'      => 'tab_types',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_types_title',
			'label' => 'Заголовок',
			'name'  => 'ooc_types_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_outofcourt_ooc_types_items',
			'label' => 'Список',
			'name'  => 'ooc_types_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_types_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'text',
				),
			),
		),
		array(
			'key'       => 'field_outofcourt_tab_eligibility',
			'label'     => 'Кому подходит',
			'name'      => 'tab_eligibility',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_eligibility_title',
			'label' => 'Заголовок',
			'name'  => 'ooc_eligibility_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_eligibility_items',
			'label' => 'Пункты',
			'name'  => 'ooc_eligibility_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_eligibility_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_outofcourt_tab_consequences',
			'label'     => 'Последствия',
			'name'      => 'tab_consequences',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_consequences_title',
			'label' => 'Заголовок',
			'name'  => 'ooc_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_consequences_items',
			'label' => 'Пункты',
			'name'  => 'ooc_consequences_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_consequences_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_outofcourt_tab_discharge',
			'label'     => 'Порядок работы',
			'name'      => 'tab_discharge',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_discharge_title',
			'label' => 'Заголовок',
			'name'  => 'ooc_discharge_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_discharge_span',
			'label' => 'Выделение',
			'name'  => 'ooc_discharge_span',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_discharge_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'ooc_discharge_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_discharge_steps',
			'label' => 'Шаги',
			'name'  => 'ooc_discharge_steps',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_discharge_steps_step_title',
					'label' => 'Название',
					'name'  => 'step_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_outofcourt_ooc_discharge_steps_step_desc',
					'label' => 'Описание',
					'name'  => 'step_desc',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_outofcourt_tab_action',
			'label'     => 'Призыв',
			'name'      => 'tab_action',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_action_title',
			'label' => 'Заголовок',
			'name'  => 'ooc_action_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_outofcourt_ooc_action_btn',
			'label' => 'Кнопка',
			'name'  => 'ooc_action_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_outofcourt_tab_faq',
			'label'     => 'FAQ',
			'name'      => 'tab_faq',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_faq_title',
			'label' => 'Заголовок',
			'name'  => 'ooc_faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_faq_items',
			'label' => 'Вопросы и ответы',
			'name'  => 'ooc_faq_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_outofcourt_ooc_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_outofcourt_tab_calc',
			'label'     => 'Калькулятор',
			'name'      => 'tab_calc',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_calc_title',
			'label' => 'Заголовок',
			'name'  => 'ooc_calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_calc_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'ooc_calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_calc_btn',
			'label' => 'Кнопка',
			'name'  => 'ooc_calc_btn',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_outofcourt_tab_callback',
			'label'     => 'Форма',
			'name'      => 'tab_callback',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_outofcourt_ooc_callback_title',
			'label' => 'Заголовок формы',
			'name'  => 'ooc_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-outofcourt.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Партнёры ───
acf_add_local_field_group( array(
	'key'   => 'group_partners',
	'title' => 'Партнёры',
	'fields' => array(
		array(
			'key'       => 'field_partners_tab_hero',
			'label'     => 'Hero',
			'name'      => 'tab_hero',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_partners_partners_hero_title',
			'label' => 'Заголовок (начало)',
			'name'  => 'partners_hero_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_hero_span',
			'label' => 'Заголовок (выделение)',
			'name'  => 'partners_hero_span',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_hero_tail',
			'label' => 'Заголовок (конец)',
			'name'  => 'partners_hero_tail',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_hero_image',
			'label' => 'Изображение',
			'name'  => 'partners_hero_image',
			'type'  => 'image',
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
		),
		array(
			'key'       => 'field_partners_tab_levels',
			'label'     => 'Уровни партнёрства',
			'name'      => 'tab_levels',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_partners_partners_levels_title',
			'label' => 'Заголовок',
			'name'  => 'partners_levels_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_levels',
			'label' => 'Уровни',
			'name'  => 'partners_levels',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_partners_partners_levels_level_name',
					'label' => 'Название',
					'name'  => 'level_name',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_partners_partners_levels_level_cond',
					'label' => 'Условие',
					'name'  => 'level_cond',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_partners_partners_levels_level_pay',
					'label' => 'Вознаграждение',
					'name'  => 'level_pay',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_partners_partners_levels_level_bonus',
					'label' => 'Бонус',
					'name'  => 'level_bonus',
					'type'  => 'text',
				),
			),
		),
		array(
			'key'       => 'field_partners_tab_benefits',
			'label'     => 'Преимущества',
			'name'      => 'tab_benefits',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_partners_partners_benefits_title',
			'label' => 'Заголовок',
			'name'  => 'partners_benefits_title',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_partners_tab_proof',
			'label'     => 'Доказательства выплат',
			'name'      => 'tab_proof',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_partners_partners_proof_title',
			'label' => 'Заголовок (до)',
			'name'  => 'partners_proof_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_proof_span',
			'label' => 'Заголовок (выделение)',
			'name'  => 'partners_proof_span',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_proof_items',
			'label' => 'Скриншоты',
			'name'  => 'partners_proof_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_partners_partners_proof_items_proof_image',
					'label' => 'Изображение',
					'name'  => 'proof_image',
					'type'  => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_partners_partners_proof_items_proof_text',
					'label' => 'Текст',
					'name'  => 'proof_text',
					'type'  => 'text',
				),
			),
		),
		array(
			'key'       => 'field_partners_tab_for_who',
			'label'     => 'Для кого',
			'name'      => 'tab_for_who',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_partners_partners_for_title',
			'label' => 'Заголовок',
			'name'  => 'partners_for_title',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_partners_tab_faq',
			'label'     => 'FAQ',
			'name'      => 'tab_faq',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_partners_partners_faq_title',
			'label' => 'Заголовок',
			'name'  => 'partners_faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_faq_items',
			'label' => 'Вопросы и ответы',
			'name'  => 'partners_faq_items',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_partners_partners_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_partners_partners_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_partners_tab_calc',
			'label'     => 'Калькулятор',
			'name'      => 'tab_calc',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_partners_partners_calc_title',
			'label' => 'Заголовок',
			'name'  => 'partners_calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_calc_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'partners_calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_partners_tab_callback',
			'label'     => 'Форма',
			'name'      => 'tab_callback',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_partners_partners_callback_title',
			'label' => 'Заголовок формы',
			'name'  => 'partners_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-partners.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Анкета ───
acf_add_local_field_group( array(
	'key'   => 'group_questionnaire',
	'title' => 'Анкета',
	'fields' => array(
		array(
			'key'       => 'field_questionnaire_tab_content',
			'label'     => 'Содержимое',
			'name'      => 'tab_content',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_questionnaire_quest_title',
			'label' => 'Заголовок страницы',
			'name'  => 'quest_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_questionnaire_quest_notice',
			'label' => 'Уведомление',
			'name'  => 'quest_notice',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_questionnaire_quest_btn',
			'label' => 'Кнопка отправки',
			'name'  => 'quest_btn',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-questionnaire.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );

// ─── Инструкции ───
acf_add_local_field_group( array(
	'key'   => 'group_instructions',
	'title' => 'Инструкции',
	'fields' => array(
		array(
			'key'       => 'field_instructions_tab_header',
			'label'     => 'Заголовок',
			'name'      => 'tab_header',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_instructions_instr_title',
			'label' => 'Заголовок H1',
			'name'  => 'instr_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'instr_subtitle',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_instructions_instr_eligibility_title',
			'label' => 'Кому подходит: заголовок',
			'name'  => 'instr_eligibility_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_situations_title',
			'label' => 'Типовые ситуации: заголовок',
			'name'  => 'instr_situations_title',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_instructions_tab_statement',
			'label'     => 'Составление заявления',
			'name'      => 'tab_statement',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_instructions_instr_statement_title',
			'label' => 'Заголовок',
			'name'  => 'instr_statement_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_before_court_title',
			'label' => 'Перед судом: заголовок',
			'name'  => 'instr_before_court_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_process_title',
			'label' => 'Способы подачи: заголовок',
			'name'  => 'instr_process_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_first_session_title',
			'label' => 'Первое заседание: заголовок',
			'name'  => 'instr_first_session_title',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_instructions_tab_restructuring',
			'label'     => 'Реструктуризация',
			'name'      => 'tab_restructuring',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_instructions_instr_restructuring_title',
			'label' => 'Процедура: заголовок',
			'name'  => 'instr_restructuring_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_repayment_title',
			'label' => 'Погашение долгов: заголовок',
			'name'  => 'instr_repayment_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_repayment_consequences_title',
			'label' => 'Последствия выплаты: заголовок',
			'name'  => 'instr_repayment_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_steps',
			'label' => 'Этапы',
			'name'  => 'instr_steps',
			'type'  => 'repeater',
			'button_label' => 'Добавить',
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key'   => 'field_instructions_instr_steps_step_title',
					'label' => 'Название',
					'name'  => 'step_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_instructions_instr_steps_step_content',
					'label' => 'Описание',
					'name'  => 'step_content',
					'type'  => 'textarea',
				),
			),
		),
		array(
			'key'       => 'field_instructions_tab_realization',
			'label'     => 'Реализация имущества',
			'name'      => 'tab_realization',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_instructions_instr_property_realization_title',
			'label' => 'Процедура: заголовок',
			'name'  => 'instr_property_realization_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_not_writeoff_title',
			'label' => 'Банкрот ≠ списание: заголовок',
			'name'  => 'instr_not_writeoff_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_negative_consequences_title',
			'label' => 'Негативные последствия: заголовок',
			'name'  => 'instr_negative_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_realization_timeline_title',
			'label' => 'Сроки: заголовок',
			'name'  => 'instr_realization_timeline_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_writeoff_consequences_title',
			'label' => 'Последствия списания: заголовок',
			'name'  => 'instr_writeoff_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'       => 'field_instructions_tab_callback',
			'label'     => 'Форма',
			'name'      => 'tab_callback',
			'type'      => 'tab',
			'placement' => 'top',
			'endpoint'  => 0,
		),
		array(
			'key'   => 'field_instructions_instr_callback_title',
			'label' => 'Заголовок формы',
			'name'  => 'instr_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-instructions.php',
	) ) ),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
) );
