<?php
if ( ! function_exists('acf_add_local_field_group') ) return;

// ─── О компании ───
acf_add_local_field_group( array(
	'key'   => 'group_company',
	'title' => 'О компании',
	'fields' => array(
		array(
			'key'   => 'field_company_team_title',
			'label' => 'Команда: заголовок',
			'name'  => 'team_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_team_title_span',
			'label' => 'Команда: заголовок (выделение)',
			'name'  => 'team_title_span',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_team_subtitle',
			'label' => 'Команда: подзаголовок',
			'name'  => 'team_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_team_members',
			'label' => 'Члены команды',
			'name'  => 'team_members',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_company_team_members_member_image',
					'label' => 'Фото',
					'name'  => 'member_image',
					'type'  => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_company_team_members_member_name',
					'label' => 'Имя',
					'name'  => 'member_name',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_company_team_members_member_link',
					'label' => 'Ссылка',
					'name'  => 'member_link',
					'type'  => 'url',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_company_action_title',
			'label' => 'Блок-призыв: заголовок',
			'name'  => 'action_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_company_action_btn',
			'label' => 'Блок-призыв: кнопка',
			'name'  => 'action_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_writeoff_h1',
			'label' => 'Списание: заголовок H1',
			'name'  => 'writeoff_h1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_writeoff_h2',
			'label' => 'Списание: описание',
			'name'  => 'writeoff_h2',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_company_writeoff_h3',
			'label' => 'Списание: призыв',
			'name'  => 'writeoff_h3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_writeoff_h3_span',
			'label' => 'Списание: призыв (выделение)',
			'name'  => 'writeoff_h3_span',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_callback_title',
			'label' => 'Форма: заголовок',
			'name'  => 'callback_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_company_callback_title_span',
			'label' => 'Форма: заголовок (выделение)',
			'name'  => 'callback_title_span',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-company.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Контакты ───
acf_add_local_field_group( array(
	'key'   => 'group_contacts',
	'title' => 'Контакты',
	'fields' => array(
		array(
			'key'   => 'field_contacts_contacts_page_title',
			'label' => 'Заголовок страницы',
			'name'  => 'contacts_page_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_form_title',
			'label' => 'Форма: заголовок',
			'name'  => 'contacts_form_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_contacts_contacts_address_label',
			'label' => 'Адрес: метка',
			'name'  => 'contacts_address_label',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_address',
			'label' => 'Адрес',
			'name'  => 'contacts_address',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_phone_label',
			'label' => 'Телефон: метка',
			'name'  => 'contacts_phone_label',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_phone',
			'label' => 'Телефон',
			'name'  => 'contacts_phone',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_phone_note',
			'label' => 'Телефон: примечание',
			'name'  => 'contacts_phone_note',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_email_label',
			'label' => 'Почта: метка',
			'name'  => 'contacts_email_label',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_contacts_contacts_email',
			'label' => 'Email',
			'name'  => 'contacts_email',
			'type'  => 'email',
		),
		array(
			'key'   => 'field_contacts_contacts_cta',
			'label' => 'CTA текст',
			'name'  => 'contacts_cta',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-contacts.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Карточка предприятия ───
acf_add_local_field_group( array(
	'key'   => 'group_organization',
	'title' => 'Карточка предприятия',
	'fields' => array(
		array(
			'key'   => 'field_organization_org_page_title',
			'label' => 'Заголовок страницы',
			'name'  => 'org_page_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_title',
			'label' => 'Банковские реквизиты: заголовок',
			'name'  => 'org_bank_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_name',
			'label' => 'Банк: наименование',
			'name'  => 'org_bank_name',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_account',
			'label' => 'Расчетный счет',
			'name'  => 'org_bank_account',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_corr',
			'label' => 'Корреспондентский счет',
			'name'  => 'org_bank_corr',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_dept',
			'label' => 'Подразделение',
			'name'  => 'org_bank_dept',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_bank_bik',
			'label' => 'БИК',
			'name'  => 'org_bank_bik',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_reg_title',
			'label' => 'Запись о создании: заголовок',
			'name'  => 'org_reg_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_reg_line1',
			'label' => 'Запись: строка 1',
			'name'  => 'org_reg_line1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_reg_line2',
			'label' => 'Запись: строка 2',
			'name'  => 'org_reg_line2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_reg_line3',
			'label' => 'Запись: строка 3',
			'name'  => 'org_reg_line3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_main_title',
			'label' => 'Компания: заголовок',
			'name'  => 'org_main_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_inn',
			'label' => 'ИНН',
			'name'  => 'org_inn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_kpp',
			'label' => 'КПП',
			'name'  => 'org_kpp',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_ogrn',
			'label' => 'ОГРН',
			'name'  => 'org_ogrn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_address',
			'label' => 'Адрес фактический',
			'name'  => 'org_address',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_organization_org_btn',
			'label' => 'Кнопка оплаты',
			'name'  => 'org_btn',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-organization.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Оплата ───
acf_add_local_field_group( array(
	'key'   => 'group_payment',
	'title' => 'Оплата',
	'fields' => array(
		array(
			'key'   => 'field_payment_payment_title',
			'label' => 'Заголовок H1',
			'name'  => 'payment_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_payment_payment_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'payment_subtitle',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_payment_payment_btn',
			'label' => 'Кнопка',
			'name'  => 'payment_btn',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-payment.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── База знаний ───
acf_add_local_field_group( array(
	'key'   => 'group_help',
	'title' => 'База знаний',
	'fields' => array(
		array(
			'key'   => 'field_help_help_title',
			'label' => 'Заголовок страницы',
			'name'  => 'help_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_help_help_title_span',
			'label' => 'Заголовок (выделение)',
			'name'  => 'help_title_span',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_help_help_articles',
			'label' => 'Статьи',
			'name'  => 'help_articles',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_help_help_articles_article_image',
					'label' => 'Изображение',
					'name'  => 'article_image',
					'type'  => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_help_help_articles_article_text',
					'label' => 'Текст',
					'name'  => 'article_text',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_help_help_articles_article_link',
					'label' => 'Ссылка',
					'name'  => 'article_link',
					'type'  => 'url',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_help_help_callback_title',
			'label' => 'Форма: заголовок',
			'name'  => 'help_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-help.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Главная страница ───
acf_add_local_field_group( array(
	'key'   => 'group_front_page',
	'title' => 'Главная страница',
	'fields' => array(
		array(
			'key'   => 'field_front_page_hero_title',
			'label' => 'Hero: заголовок H1',
			'name'  => 'hero_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_subtitle',
			'label' => 'Hero: подзаголовок H2',
			'name'  => 'hero_subtitle',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_btn',
			'label' => 'Hero: кнопка',
			'name'  => 'hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat1_num',
			'label' => 'Hero: статистика 1 (число)',
			'name'  => 'hero_stat1_num',
			'type'  => 'number',
		),
		array(
			'key'   => 'field_front_page_hero_stat1_text',
			'label' => 'Hero: статистика 1 (текст)',
			'name'  => 'hero_stat1_text',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat2_before',
			'label' => 'Hero: статистика 2 (до числа)',
			'name'  => 'hero_stat2_before',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat2_num',
			'label' => 'Hero: статистика 2 (число)',
			'name'  => 'hero_stat2_num',
			'type'  => 'number',
		),
		array(
			'key'   => 'field_front_page_hero_stat2_after',
			'label' => 'Hero: статистика 2 (после)',
			'name'  => 'hero_stat2_after',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat3_before',
			'label' => 'Hero: статистика 3 (до числа)',
			'name'  => 'hero_stat3_before',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_stat3_num',
			'label' => 'Hero: статистика 3 (число)',
			'name'  => 'hero_stat3_num',
			'type'  => 'number',
		),
		array(
			'key'   => 'field_front_page_hero_stat3_after',
			'label' => 'Hero: статистика 3 (после)',
			'name'  => 'hero_stat3_after',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_box1',
			'label' => 'Hero: блок 1',
			'name'  => 'hero_box1',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_box2',
			'label' => 'Hero: блок 2',
			'name'  => 'hero_box2',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_box3',
			'label' => 'Hero: блок 3',
			'name'  => 'hero_box3',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_hero_review1_text',
			'label' => 'Hero: отзывы 1 (текст)',
			'name'  => 'hero_review1_text',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_review1_link',
			'label' => 'Hero: отзывы 1 (ссылка)',
			'name'  => 'hero_review1_link',
			'type'  => 'url',
		),
		array(
			'key'   => 'field_front_page_hero_review2_text',
			'label' => 'Hero: отзывы 2 (текст)',
			'name'  => 'hero_review2_text',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_hero_review2_link',
			'label' => 'Hero: отзывы 2 (ссылка)',
			'name'  => 'hero_review2_link',
			'type'  => 'url',
		),
		array(
			'key'   => 'field_front_page_amnesty_title',
			'label' => 'Амнистия: заголовок',
			'name'  => 'amnesty_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_amnesty_cards',
			'label' => 'Амнистия: карточки',
			'name'  => 'amnesty_cards',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_amnesty_cards_card_num',
					'label' => 'Номер',
					'name'  => 'card_num',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_amnesty_cards_card_title',
					'label' => 'Заголовок',
					'name'  => 'card_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_amnesty_cards_card_text',
					'label' => 'Описание',
					'name'  => 'card_text',
					'type'  => 'text',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_front_page_amnesty_btn',
			'label' => 'Амнистия: кнопка',
			'name'  => 'amnesty_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_discharge_title',
			'label' => 'Списание: заголовок',
			'name'  => 'discharge_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_discharge_subtitle',
			'label' => 'Списание: подзаголовок',
			'name'  => 'discharge_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_discharge_steps',
			'label' => 'Списание: шаги',
			'name'  => 'discharge_steps',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_discharge_steps_step_text',
					'label' => 'Шаг',
					'name'  => 'step_text',
					'type'  => 'text',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_front_page_trust_title',
			'label' => 'Доверие: заголовок',
			'name'  => 'trust_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_trust_items',
			'label' => 'Доверие: преимущества',
			'name'  => 'trust_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_trust_items_item_title',
					'label' => 'Заголовок',
					'name'  => 'item_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_trust_items_item_text',
					'label' => 'Текст',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_front_page_action_title',
			'label' => 'Призыв: заголовок',
			'name'  => 'action_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_front_page_action_btn',
			'label' => 'Призыв: кнопка',
			'name'  => 'action_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_history_title',
			'label' => 'Истории: заголовок',
			'name'  => 'history_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_history_cases',
			'label' => 'Истории: кейсы',
			'name'  => 'history_cases',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_history_cases_case_title',
					'label' => 'Заголовок',
					'name'  => 'case_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_image',
					'label' => 'Фото',
					'name'  => 'case_image',
					'type'  => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_problem',
					'label' => 'Проблема',
					'name'  => 'case_problem',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_solution',
					'label' => 'Решение',
					'name'  => 'case_solution',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_term',
					'label' => 'Срок',
					'name'  => 'case_term',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_result',
					'label' => 'Итог',
					'name'  => 'case_result',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_history_cases_case_btn',
					'label' => 'Кнопка',
					'name'  => 'case_btn',
					'type'  => 'text',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_front_page_case_stat1',
			'label' => 'Цифры: долгов списано',
			'name'  => 'case_stat1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_case_stat2',
			'label' => 'Цифры: средний срок',
			'name'  => 'case_stat2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_case_stat3',
			'label' => 'Цифры: клиентов',
			'name'  => 'case_stat3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_case_btn',
			'label' => 'Цифры: кнопка',
			'name'  => 'case_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_faq_title',
			'label' => 'FAQ: заголовок',
			'name'  => 'faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_faq_items',
			'label' => 'FAQ: вопросы',
			'name'  => 'faq_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_front_page_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_front_page_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_front_page_calc_title',
			'label' => 'Калькулятор: заголовок',
			'name'  => 'calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_calc_subtitle',
			'label' => 'Калькулятор: подзаголовок',
			'name'  => 'calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_front_page_callback_title',
			'label' => 'Форма: заголовок',
			'name'  => 'callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'front-page.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Судебное банкротство ───
acf_add_local_field_group( array(
	'key'   => 'group_court',
	'title' => 'Судебное банкротство',
	'fields' => array(
		array(
			'key'   => 'field_court_court_hero_title',
			'label' => 'Герой: заголовок H1',
			'name'  => 'court_hero_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_subtitle',
			'label' => 'Герой: подзаголовок',
			'name'  => 'court_hero_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_stat1',
			'label' => 'Герой: статус 1',
			'name'  => 'court_hero_stat1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_stat2',
			'label' => 'Герой: статус 2',
			'name'  => 'court_hero_stat2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_stat3',
			'label' => 'Герой: статус 3',
			'name'  => 'court_hero_stat3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_btn',
			'label' => 'Герой: кнопка',
			'name'  => 'court_hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_hero_desc',
			'label' => 'Герой: описание',
			'name'  => 'court_hero_desc',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_court_types_title',
			'label' => 'Типы долгов: заголовок',
			'name'  => 'court_types_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_court_types_items',
			'label' => 'Типы долгов: список',
			'name'  => 'court_types_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_types_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'text',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_court_eligibility_title',
			'label' => 'Кому подходит: заголовок',
			'name'  => 'court_eligibility_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_eligibility_items',
			'label' => 'Кому подходит: пункты',
			'name'  => 'court_eligibility_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_eligibility_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_court_consequences_title',
			'label' => 'Последствия: заголовок',
			'name'  => 'court_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_consequences_items',
			'label' => 'Последствия: пункты',
			'name'  => 'court_consequences_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_consequences_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_court_action_title',
			'label' => 'Призыв: заголовок',
			'name'  => 'court_action_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_court_action_btn',
			'label' => 'Призыв: кнопка',
			'name'  => 'court_action_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_stages_title',
			'label' => 'Этапы: заголовок',
			'name'  => 'court_stages_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_stages_items',
			'label' => 'Этапы',
			'name'  => 'court_stages_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_stages_items_stage_title',
					'label' => 'Название',
					'name'  => 'stage_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_court_stages_items_stage_term',
					'label' => 'Срок',
					'name'  => 'stage_term',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_court_stages_items_stage_desc',
					'label' => 'Описание',
					'name'  => 'stage_desc',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_court_result_title',
			'label' => 'Результат: заголовок',
			'name'  => 'court_result_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_result_text',
			'label' => 'Результат: текст',
			'name'  => 'court_result_text',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_court_faq_title',
			'label' => 'FAQ: заголовок',
			'name'  => 'court_faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_faq_items',
			'label' => 'FAQ: вопросы',
			'name'  => 'court_faq_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_court_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_court_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_court_calc_title',
			'label' => 'Калькулятор: заголовок',
			'name'  => 'court_calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_calc_subtitle',
			'label' => 'Калькулятор: подзаголовок',
			'name'  => 'court_calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_calc_btn',
			'label' => 'Калькулятор: кнопка',
			'name'  => 'court_calc_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_court_callback_title',
			'label' => 'Форма: заголовок',
			'name'  => 'court_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-court.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Детали судебного банкротства ───
acf_add_local_field_group( array(
	'key'   => 'group_court_details',
	'title' => 'Детали судебного банкротства',
	'fields' => array(
		array(
			'key'   => 'field_court_details_cd_hero_title',
			'label' => 'Герой: H1',
			'name'  => 'cd_hero_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_cd_hero_subtitle',
			'label' => 'Герой: подзаголовок',
			'name'  => 'cd_hero_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_cd_hero_btn',
			'label' => 'Герой: кнопка',
			'name'  => 'cd_hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_cd_hero_desc',
			'label' => 'Герой: описание',
			'name'  => 'cd_hero_desc',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_details_cd_types_title',
			'label' => 'Типы: заголовок',
			'name'  => 'cd_types_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_details_cd_types_items',
			'label' => 'Типы: список',
			'name'  => 'cd_types_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_cd_types_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'text',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_details_cd_eligibility_title',
			'label' => 'Кому подходит: заголовок',
			'name'  => 'cd_eligibility_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_cd_eligibility_items',
			'label' => 'Кому подходит: пункты',
			'name'  => 'cd_eligibility_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_cd_eligibility_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_details_cd_consequences_title',
			'label' => 'Последствия: заголовок',
			'name'  => 'cd_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_cd_consequences_items',
			'label' => 'Последствия: пункты',
			'name'  => 'cd_consequences_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_cd_consequences_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_details_cd_stages_title',
			'label' => 'Этапы: заголовок',
			'name'  => 'cd_stages_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_cd_stages_items',
			'label' => 'Этапы',
			'name'  => 'cd_stages_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_cd_stages_items_stage_title',
					'label' => 'Название',
					'name'  => 'stage_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_details_cd_stages_items_stage_term',
					'label' => 'Срок',
					'name'  => 'stage_term',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_details_cd_stages_items_stage_desc',
					'label' => 'Описание',
					'name'  => 'stage_desc',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_details_cd_result_title',
			'label' => 'Результат: заголовок',
			'name'  => 'cd_result_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_cd_result_text',
			'label' => 'Результат: текст',
			'name'  => 'cd_result_text',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_court_details_cd_faq_title',
			'label' => 'FAQ: заголовок',
			'name'  => 'cd_faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_court_details_cd_faq_items',
			'label' => 'FAQ: вопросы',
			'name'  => 'cd_faq_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_court_details_cd_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_court_details_cd_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_court_details_cd_callback_title',
			'label' => 'Форма: заголовок',
			'name'  => 'cd_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-court-details.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Внесудебное банкротство ───
acf_add_local_field_group( array(
	'key'   => 'group_outofcourt',
	'title' => 'Внесудебное банкротство',
	'fields' => array(
		array(
			'key'   => 'field_outofcourt_ooc_hero_title',
			'label' => 'Герой: H1',
			'name'  => 'ooc_hero_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_subtitle',
			'label' => 'Герой: подзаголовок',
			'name'  => 'ooc_hero_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_stat1',
			'label' => 'Герой: статус 1',
			'name'  => 'ooc_hero_stat1',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_stat2',
			'label' => 'Герой: статус 2',
			'name'  => 'ooc_hero_stat2',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_stat3',
			'label' => 'Герой: статус 3',
			'name'  => 'ooc_hero_stat3',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_btn',
			'label' => 'Герой: кнопка',
			'name'  => 'ooc_hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_hero_desc',
			'label' => 'Герой: описание',
			'name'  => 'ooc_hero_desc',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_outofcourt_ooc_types_title',
			'label' => 'Типы: заголовок',
			'name'  => 'ooc_types_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_outofcourt_ooc_types_items',
			'label' => 'Типы: список',
			'name'  => 'ooc_types_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_types_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'text',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_outofcourt_ooc_eligibility_title',
			'label' => 'Кому подходит: заголовок',
			'name'  => 'ooc_eligibility_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_eligibility_items',
			'label' => 'Кому подходит: пункты',
			'name'  => 'ooc_eligibility_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_eligibility_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_outofcourt_ooc_consequences_title',
			'label' => 'Последствия: заголовок',
			'name'  => 'ooc_consequences_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_consequences_items',
			'label' => 'Последствия: пункты',
			'name'  => 'ooc_consequences_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_consequences_items_item_text',
					'label' => 'Пункт',
					'name'  => 'item_text',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_outofcourt_ooc_discharge_title',
			'label' => 'Порядок работы: заголовок',
			'name'  => 'ooc_discharge_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_discharge_subtitle',
			'label' => 'Порядок работы: подзаголовок',
			'name'  => 'ooc_discharge_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_discharge_steps',
			'label' => 'Порядок работы: шаги',
			'name'  => 'ooc_discharge_steps',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_discharge_steps_step_title',
					'label' => 'Шаг: название',
					'name'  => 'step_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_outofcourt_ooc_discharge_steps_step_desc',
					'label' => 'Шаг: описание',
					'name'  => 'step_desc',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_outofcourt_ooc_faq_title',
			'label' => 'FAQ: заголовок',
			'name'  => 'ooc_faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_faq_items',
			'label' => 'FAQ: вопросы',
			'name'  => 'ooc_faq_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_outofcourt_ooc_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_outofcourt_ooc_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_outofcourt_ooc_calc_title',
			'label' => 'Калькулятор: заголовок',
			'name'  => 'ooc_calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_calc_subtitle',
			'label' => 'Калькулятор: подзаголовок',
			'name'  => 'ooc_calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_outofcourt_ooc_callback_title',
			'label' => 'Форма: заголовок',
			'name'  => 'ooc_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-outofcourt.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Партнёры ───
acf_add_local_field_group( array(
	'key'   => 'group_partners',
	'title' => 'Партнёры',
	'fields' => array(
		array(
			'key'   => 'field_partners_partners_hero_title',
			'label' => 'Hero: заголовок',
			'name'  => 'partners_hero_title',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_partners_partners_hero_subtitle',
			'label' => 'Hero: подзаголовок',
			'name'  => 'partners_hero_subtitle',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_partners_partners_hero_btn',
			'label' => 'Hero: кнопка',
			'name'  => 'partners_hero_btn',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_hero_image',
			'label' => 'Hero: изображение',
			'name'  => 'partners_hero_image',
			'type'  => 'image',
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
		),
		array(
			'key'   => 'field_partners_partners_levels_title',
			'label' => 'Уровни: заголовок',
			'name'  => 'partners_levels_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_levels',
			'label' => 'Уровни',
			'name'  => 'partners_levels',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_partners_partners_levels_level_name',
					'label' => 'Название',
					'name'  => 'level_name',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_partners_partners_levels_level_cond',
					'label' => 'Условие',
					'name'  => 'level_cond',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_partners_partners_levels_level_pay',
					'label' => 'Вознаграждение',
					'name'  => 'level_pay',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_partners_partners_levels_level_bonus',
					'label' => 'Бонус',
					'name'  => 'level_bonus',
					'type'  => 'text',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_partners_partners_proof_title',
			'label' => 'Доказательства: заголовок',
			'name'  => 'partners_proof_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_proof_items',
			'label' => 'Доказательства',
			'name'  => 'partners_proof_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_partners_partners_proof_items_proof_image',
					'label' => 'Изображение',
					'name'  => 'proof_image',
					'type'  => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_partners_partners_proof_items_proof_text',
					'label' => 'Текст',
					'name'  => 'proof_text',
					'type'  => 'text',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_partners_partners_faq_title',
			'label' => 'FAQ: заголовок',
			'name'  => 'partners_faq_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_faq_items',
			'label' => 'FAQ: вопросы',
			'name'  => 'partners_faq_items',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_partners_partners_faq_items_faq_q',
					'label' => 'Вопрос',
					'name'  => 'faq_q',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_partners_partners_faq_items_faq_a',
					'label' => 'Ответ',
					'name'  => 'faq_a',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_partners_partners_calc_title',
			'label' => 'Калькулятор: заголовок',
			'name'  => 'partners_calc_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_calc_subtitle',
			'label' => 'Калькулятор: подзаголовок',
			'name'  => 'partners_calc_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_partners_partners_callback_title',
			'label' => 'Форма: заголовок',
			'name'  => 'partners_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-partners.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Анкета ───
acf_add_local_field_group( array(
	'key'   => 'group_questionnaire',
	'title' => 'Анкета',
	'fields' => array(
		array(
			'key'   => 'field_questionnaire_quest_title',
			'label' => 'Заголовок страницы',
			'name'  => 'quest_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_questionnaire_quest_notice',
			'label' => 'Уведомление (п.1)',
			'name'  => 'quest_notice',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_questionnaire_quest_btn',
			'label' => 'Кнопка отправки',
			'name'  => 'quest_btn',
			'type'  => 'text',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-questionnaire.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );

// ─── Инструкции ───
acf_add_local_field_group( array(
	'key'   => 'group_instructions',
	'title' => 'Инструкции',
	'fields' => array(
		array(
			'key'   => 'field_instructions_instr_title',
			'label' => 'Заголовок страницы',
			'name'  => 'instr_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_subtitle',
			'label' => 'Подзаголовок',
			'name'  => 'instr_subtitle',
			'type'  => 'textarea',
		),
		array(
			'key'   => 'field_instructions_instr_eligibility_title',
			'label' => 'Кому подходит: заголовок',
			'name'  => 'instr_eligibility_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_instructions_instr_steps',
			'label' => 'Этапы процедуры',
			'name'  => 'instr_steps',
			'type'  => 'repeater',
			'sub_fields' => array(
				array(
					'key'   => 'field_instructions_instr_steps_step_title',
					'label' => 'Название этапа',
					'name'  => 'step_title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_instructions_instr_steps_step_content',
					'label' => 'Содержание',
					'name'  => 'step_content',
					'type'  => 'textarea',
				),
			),
			'button_label' => 'Добавить',
			'layout' => 'table',
		),
		array(
			'key'   => 'field_instructions_instr_callback_title',
			'label' => 'Форма: заголовок',
			'name'  => 'instr_callback_title',
			'type'  => 'textarea',
		),
	),
	'location' => array( array( array(
		'param'    => 'page_template',
		'operator' => '==',
		'value'    => 'page-instructions.php',
	) ) ),
	'menu_order'          => 0,
	'position'            => 'normal',
	'style'               => 'default',
	'label_placement'     => 'top',
	'instruction_placement' => 'label',
) );
